apiVersion: v1
kind: Service
metadata:
  name: {{ include "aura.fullname" . }}-frontend
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "aura.labels" . | nindent 4 }}
    app.kubernetes.io/component: frontend
spec:
  type: ClusterIP
  selector:
    app.kubernetes.io/name: {{ include "aura.name" . }}-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
    - name: http
      port: {{ .Values.frontend.port }}
      targetPort: http
      protocol: TCP
