apiVersion: v1
kind: Service
metadata:
  name: {{ include "aura.fullname" . }}-frontend
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: aura-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.frontend.service.type }}
  selector:
    app.kubernetes.io/name: aura-frontend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.frontend.service.port }}
    targetPort: 80
