apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aura.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: aura-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  {{- if not .Values.backend.autoscaling.enabled }}
  replicas: {{ .Values.backend.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      app.kubernetes.io/name: aura-backend
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: aura-backend
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      {{- with .Values.global.imagePullSecrets }}
      imagePullSecrets:
{{ toYaml . | indent 6 }}
      {{- end }}
      containers:
      - name: backend
        image: "{{ .Values.backend.image.repository }}:{{ .Values.backend.image.tag }}"
        imagePullPolicy: {{ .Values.backend.image.pullPolicy }}
        ports:
        - containerPort: 8000
          name: http
        env:
        - name: MONGO_URL
          value: "mongodb://{{ include "aura.fullname" . }}-mongodb:{{ .Values.mongodb.service.port }}"
        envFrom:
        - secretRef:
            name: {{ .Values.backend.env.existingSecret }}
        resources:
{{ toYaml .Values.backend.resources | indent 10 }}
        startupProbe:
          httpGet:
            path: /health/live
            port: http
          periodSeconds: 5
          failureThreshold: 30
        livenessProbe:
          httpGet:
            path: /health/live
            port: http
          initialDelaySeconds: 30
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /health/ready
            port: http
          initialDelaySeconds: 15
          periodSeconds: 10
