{{- if .Values.backend.env.createSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.backend.env.existingSecret }}
  namespace: {{ .Values.global.namespace }}
type: Opaque
stringData:
  DB_NAME: {{ .Values.backend.env.values.DB_NAME | quote }}
  CORS_ORIGINS: {{ .Values.backend.env.values.CORS_ORIGINS | quote }}
  JWT_SECRET: {{ .Values.backend.env.values.JWT_SECRET | quote }}
  EMERGENT_LLM_KEY: {{ .Values.backend.env.values.EMERGENT_LLM_KEY | quote }}
  RAZORPAY_KEY_ID: {{ .Values.backend.env.values.RAZORPAY_KEY_ID | quote }}
  RAZORPAY_KEY_SECRET: {{ .Values.backend.env.values.RAZORPAY_KEY_SECRET | quote }}
  CLOUDINARY_CLOUD_NAME: {{ .Values.backend.env.values.CLOUDINARY_CLOUD_NAME | quote }}
  CLOUDINARY_API_KEY: {{ .Values.backend.env.values.CLOUDINARY_API_KEY | quote }}
  CLOUDINARY_API_SECRET: {{ .Values.backend.env.values.CLOUDINARY_API_SECRET | quote }}
  OPENAI_API_KEY: {{ .Values.backend.env.values.OPENAI_API_KEY | quote }}
  SENDER_EMAIL: {{ .Values.backend.env.values.SENDER_EMAIL | quote }}
  SENDER_PASSWORD: {{ .Values.backend.env.values.SENDER_PASSWORD | quote }}
  SMTP_SERVER: {{ .Values.backend.env.values.SMTP_SERVER | quote }}
  SMTP_PORT: {{ .Values.backend.env.values.SMTP_PORT | quote }}
{{- end }}
