apiVersion: v1
kind: Service
metadata:
  name: {{ include "aura.fullname" . }}-backend
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: aura-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  type: {{ .Values.backend.service.type }}
  selector:
    app.kubernetes.io/name: aura-backend
    app.kubernetes.io/instance: {{ .Release.Name }}
  ports:
  - name: http
    port: {{ .Values.backend.service.port }}
    targetPort: 8000
