{{- if and .Values.mongodb.enabled .Values.mongodb.persistence.enabled }}
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: {{ include "aura.fullname" . }}-mongodb
  namespace: {{ .Values.global.namespace }}
  labels:
    app.kubernetes.io/name: aura-mongodb
    app.kubernetes.io/instance: {{ .Release.Name }}
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: {{ .Values.mongodb.persistence.size }}
{{- if .Values.mongodb.persistence.storageClassName }}
  storageClassName: {{ .Values.mongodb.persistence.storageClassName | quote }}
{{- end }}
{{- end }}